# WeatherPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [6]:
#! pip install apikey
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress

# Import API key
from apikey import weather_api_key

# Incorporated citipy to determine city based on latitude and longitude
from citipy import citipy
from pprint import pprint

# Output File (CSV)
output_data_file = "output_data/cities.csv"

# Range of latitudes and longitudes
lat_range = (-90, 90)
lng_range = (-180, 180)

ImportError: cannot import name 'weather_api_key' from 'apikey' (C:\Users\vertt\anaconda3\lib\site-packages\apikey\__init__.py)

## Generate Cities List

In [2]:
# List for holding for holding respective information
lat_lngs = []
cities = []
latlist =[]
lnglist =[]
maxTemps = []
humidity = []
cloudiness = []
windSpeeds = []
countries = []
dates = []
#testCities = ['Atlanta','butaritari']
baseURL = "https://api.openweathermap.org/data/2.5/weather?"
#baseURL= "https://api.openweathermap.org/data/3.0/onecall?"
units = 'imperial'
city = []

# Create a set of random lat and lng combinations
lats = np.random.uniform(lat_range[0], lat_range[1], size=1500)
lngs = np.random.uniform(lng_range[0], lng_range[1], size=1500)
lat_lngs = zip(lats, lngs)

# Identify nearest city for each lat, lng combination
for lat_lng in lat_lngs:
    city = citipy.nearest_city(lat_lng[0], lat_lng[1]).city_name
    
    # If the city is unique, then add it to a our cities list
    if city not in cities:
        cities.append(city)

citiesToProcess = pd.DataFrame (cities, columns = ['City'])

#setup the remaining columns 
citiesToProcess["Lat"]="" 
citiesToProcess["Lng"]="" 
citiesToProcess["Max Temp"]="" 
citiesToProcess["Humidity"]="" 
citiesToProcess["Cloudiness"]="" 
citiesToProcess["Wind Speed"]="" 
citiesToProcess["Country"]="" 
citiesToProcess["Date"]="" 
citiesToProcess.head()

            City Lat Lng Max Temp Humidity Cloudiness Wind Speed Country Date
0      jamestown
1      taolanaro
2          kapaa
3       hermanus
4  palabuhanratu

In [3]:
len(cities) # the length of expected items

648

In [4]:
citiesToProcess.head()

            City Lat Lng Max Temp Humidity Cloudiness Wind Speed Country Date
0      jamestown
1      taolanaro
2          kapaa
3       hermanus
4  palabuhanratu

In [10]:
 # setup parameters for passing to API to generate URL based on respective city passed into URL
baseURL = "https://api.openweathermap.org/data/2.5/weather?"
units="imperial"

parameters = {
      "units":units,
     "appid":weather_api_key,
}
group = 1
recordCount = 1

print (f"Beginning Data Retrieval ")
print (f"------------------------ ")
for index, row in citiesToProcess.iterrows():
    #print(index)
    if recordCount < 50 :
        parameters['q'] = citiesToProcess.loc[index,'City']
    
        print (f"Processing Record {recordCount} of Set  {group} | {citiesToProcess.loc[index,'City']} ")
        getCityData = requests.get(baseURL,params=parameters).json()

        try:
            #grab infomration from results key 
            citiesToProcess.loc[index,'City']=getCityData['name']
            citiesToProcess.loc[index,'Lat']=getCityData['coord']['lat']
            citiesToProcess.loc[index,'Lng']=getCityData['coord']['lon']
            citiesToProcess.loc[index,'Max Temp']=getCityData['main']['temp_max']
            citiesToProcess.loc[index,'Humidity']=getCityData['main']['humidity']
            citiesToProcess.loc[index,'Cloudiness']=getCityData['clouds']['all']
            citiesToProcess.loc[index,'Wind Speed']=getCityData['wind']['speed']
            citiesToProcess.loc[index,'Country']=getCityData['sys']['country']
            citiesToProcess.loc[index,'Date']=getCityData['dt']
            
            recordCount +=1   # control count for the conditional 
            time.sleep(2)   # pause between number of records processed

        except (KeyError,IndexError):
            print("City not found. Skipping...")
    else:
        recordCount  = 1
        group += 1
        
            

    #Processing Record 1 of Set 1 | butaritari
    
print (f"------------------------ ")
print (f"Data Retrieval Complete ")
print (f"------------------------ ")

Beginning Data Retrieval
------------------------
Processing Record 1 of Set  1 | Jamestown
Processing Record 2 of Set  1 | taolanaro
City not found. Skipping...
Processing Record 2 of Set  1 | Kapaa
Processing Record 3 of Set  1 | hermanus
Processing Record 4 of Set  1 | palabuhanratu
City not found. Skipping...
Processing Record 4 of Set  1 | cherskiy
Processing Record 5 of Set  1 | ushuaia
Processing Record 6 of Set  1 | east london
Processing Record 7 of Set  1 | vaitupu
City not found. Skipping...
Processing Record 7 of Set  1 | dikson
Processing Record 8 of Set  1 | qaanaaq
Processing Record 9 of Set  1 | castro
Processing Record 10 of Set  1 | fairbanks
Processing Record 11 of Set  1 | rybnik
Processing Record 12 of Set  1 | atuona
Processing Record 13 of Set  1 | mar del plata
Processing Record 14 of Set  1 | busselton
Processing Record 15 of Set  1 | grand gaube
Processing Record 16 of Set  1 | el alto
Processing Record 17 of Set  1 | hobart
Processing Record 18 of Set  1 | yamada
Processing Record 19 of Set  1 | new norfolk
Processing Record 20 of Set  1 | capesterre-belle-eau
Processing Record 21 of Set  1 | vila praia de ancora
Processing Record 22 of Set  1 | meulaboh
Processing Record 23 of Set  1 | bengkulu
Processing Record 24 of Set  1 | port elizabeth
Processing Record 25 of Set  1 | jabinyanah
Processing Record 26 of Set  1 | sao filipe
Processing Record 27 of Set  1 | butaritari
Processing Record 28 of Set  1 | san antonio
Processing Record 29 of Set  1 | harrisonburg
Processing Record 30 of Set  1 | greenwood
Processing Record 31 of Set  1 | arraial do cabo
Processing Record 32 of Set  1 | lorengau
Processing Record 33 of Set  1 | vila franca do campo
Processing Record 34 of Set  1 | chanika
Processing Record 35 of Set  1 | nioki
Processing Record 36 of Set  1 | srednekolymsk
Processing Record 37 of Set  1 | severo-kurilsk
Processing Record 38 of Set  1 | san quintin
Processing Record 39 of Set  1 | bandar-e torkaman
City not found. Skipping...
Processing Record 39 of Set  1 | oksfjord
Processing Record 40 of Set  1 | rolim de moura
City not found. Skipping...
Processing Record 40 of Set  1 | tuktoyaktuk
Processing Record 41 of Set  1 | bluff
Processing Record 42 of Set  1 | aljezur
Processing Record 43 of Set  1 | marrakesh
Processing Record 44 of Set  1 | rikitea
Processing Record 45 of Set  1 | gumdag
Processing Record 46 of Set  1 | hambantota
Processing Record 47 of Set  1 | ailigandi
Processing Record 48 of Set  1 | victoria
Processing Record 49 of Set  1 | punta arenas
Processing Record 0 of Set  2 | husavik
Processing Record 1 of Set  2 | yanam
Processing Record 2 of Set  2 | christiansburg
Processing Record 3 of Set  2 | sao mateus
Processing Record 4 of Set  2 | ardahan
Processing Record 5 of Set  2 | isangel
Processing Record 6 of Set  2 | port alfred
Processing Record 7 of Set  2 | mys shmidta
City not found. Skipping...
Processing Record 7 of Set  2 | thompson
Processing Record 8 of Set  2 | belushya guba
City not found. Skipping...
Processing Record 8 of Set  2 | upernavik
Processing Record 9 of Set  2 | bambous virieux
Processing Record 10 of Set  2 | padang
Processing Record 11 of Set  2 | margate
Processing Record 12 of Set  2 | illoqqortoormiut
City not found. Skipping...
Processing Record 12 of Set  2 | el sauzal
Processing Record 13 of Set  2 | antalaha
Processing Record 14 of Set  2 | longyearbyen
Processing Record 15 of Set  2 | marienburg
Processing Record 16 of Set  2 | pandegelang
Processing Record 17 of Set  2 | saint-joseph
Processing Record 18 of Set  2 | mizdah
Processing Record 19 of Set  2 | chokurdakh
Processing Record 20 of Set  2 | pangody
Processing Record 21 of Set  2 | mutare
Processing Record 22 of Set  2 | alotau
City not found. Skipping...
Processing Record 22 of Set  2 | pagatin
Processing Record 23 of Set  2 | barrow
Processing Record 24 of Set  2 | khatanga
Processing Record 25 of Set  2 | hilo
Processing Record 26 of Set  2 | avarua
Processing Record 27 of Set  2 | sergeyevka
Processing Record 28 of Set  2 | saint george
Processing Record 29 of Set  2 | cape town
Processing Record 30 of Set  2 | provideniya
Processing Record 31 of Set  2 | katsuura
Processing Record 32 of Set  2 | saint-philippe
Processing Record 33 of Set  2 | ponta do sol
Processing Record 34 of Set  2 | batagay-alyta
Processing Record 35 of Set  2 | general pico
Processing Record 36 of Set  2 | ilulissat
Processing Record 37 of Set  2 | kahului
Processing Record 38 of Set  2 | tabialan
City not found. Skipping...
Processing Record 38 of Set  2 | hasilpur
Processing Record 39 of Set  2 | saint-pierre
Processing Record 40 of Set  2 | nevelsk
Processing Record 41 of Set  2 | sorvag
City not found. Skipping...
Processing Record 41 of Set  2 | amderma
City not found. Skipping...
Processing Record 41 of Set  2 | jomalig
City not found. Skipping...
Processing Record 41 of Set  2 | sattahip
Processing Record 42 of Set  2 | arteaga
Processing Record 43 of Set  2 | aklavik
Processing Record 44 of Set  2 | lolua
City not found. Skipping...
Processing Record 44 of Set  2 | azul
Processing Record 45 of Set  2 | kodiak
Processing Record 46 of Set  2 | hamilton
Processing Record 47 of Set  2 | muscatine
Processing Record 48 of Set  2 | chagda
City not found. Skipping...
Processing Record 48 of Set  2 | egvekinot
Processing Record 49 of Set  2 | albany
Processing Record 0 of Set  3 | jumla
Processing Record 1 of Set  3 | yar-sale
Processing Record 2 of Set  3 | puerto ayora
Processing Record 3 of Set  3 | harper
Processing Record 4 of Set  3 | poum
Processing Record 5 of Set  3 | nha trang
Processing Record 6 of Set  3 | saint anthony
Processing Record 7 of Set  3 | touros
Processing Record 8 of Set  3 | airai
Processing Record 9 of Set  3 | vaini
Processing Record 10 of Set  3 | tsihombe
City not found. Skipping...
Processing Record 10 of Set  3 | puerto narino
Processing Record 11 of Set  3 | kalabo
Processing Record 12 of Set  3 | gangotri
City not found. Skipping...
Processing Record 12 of Set  3 | santa eulalia del rio
City not found. Skipping...
Processing Record 12 of Set  3 | singaraja
Processing Record 13 of Set  3 | kabinda
Processing Record 14 of Set  3 | mae sai
Processing Record 15 of Set  3 | puerto ayacucho
Processing Record 16 of Set  3 | deutsch-wagram
Processing Record 17 of Set  3 | vila velha
Processing Record 18 of Set  3 | coquimbo
Processing Record 19 of Set  3 | grand river south east
City not found. Skipping...
Processing Record 19 of Set  3 | mount isa
Processing Record 20 of Set  3 | mataura
Processing Record 21 of Set  3 | salalah
Processing Record 22 of Set  3 | ketchikan
Processing Record 23 of Set  3 | saskylakh
Processing Record 24 of Set  3 | port blair
Processing Record 25 of Set  3 | vieques
Processing Record 26 of Set  3 | forestville
Processing Record 27 of Set  3 | carnarvon
Processing Record 28 of Set  3 | kuche
City not found. Skipping...
Processing Record 28 of Set  3 | kashi
Processing Record 29 of Set  3 | yellowknife
Processing Record 30 of Set  3 | gashua
Processing Record 31 of Set  3 | gornozavodsk
Processing Record 32 of Set  3 | kruisfontein
Processing Record 33 of Set  3 | bara
Processing Record 34 of Set  3 | biltine
Processing Record 35 of Set  3 | vostok
Processing Record 36 of Set  3 | ust-nera
Processing Record 37 of Set  3 | miandrivazo
Processing Record 38 of Set  3 | morondava
Processing Record 39 of Set  3 | rancho palos verdes
Processing Record 40 of Set  3 | cidreira
Processing Record 41 of Set  3 | attawapiskat
City not found. Skipping...
Processing Record 41 of Set  3 | miri
Processing Record 42 of Set  3 | hofn
Processing Record 43 of Set  3 | denpasar
Processing Record 44 of Set  3 | la baule-escoublac
Processing Record 45 of Set  3 | sungaipenuh
Processing Record 46 of Set  3 | grindavik
Processing Record 47 of Set  3 | kieta
Processing Record 48 of Set  3 | cururupu
Processing Record 49 of Set  3 | avera
Processing Record 0 of Set  4 | lompoc
Processing Record 1 of Set  4 | saldanha

Processing Record 2 of Set  4 | kitimat
Processing Record 3 of Set  4 | narsaq
Processing Record 4 of Set  4 | honiara
Processing Record 5 of Set  4 | tabulbah
City not found. Skipping...
Processing Record 5 of Set  4 | sao borja
Processing Record 6 of Set  4 | angarsk
Processing Record 7 of Set  4 | novyy urengoy
Processing Record 8 of Set  4 | beringovskiy
Processing Record 9 of Set  4 | lebu
Processing Record 10 of Set  4 | kavaratti
Processing Record 11 of Set  4 | boende
Processing Record 12 of Set  4 | port hardy
Processing Record 13 of Set  4 | byron bay
Processing Record 14 of Set  4 | mendahara
City not found. Skipping...
Processing Record 14 of Set  4 | eureka
Processing Record 15 of Set  4 | thunder bay
Processing Record 16 of Set  4 | nikolskoye
Processing Record 17 of Set  4 | storsteinnes
Processing Record 18 of Set  4 | doha
Processing Record 19 of Set  4 | wulanhaote
City not found. Skipping...
Processing Record 19 of Set  4 | axim
Processing Record 20 of Set  4 | palafrugell
Processing Record 21 of Set  4 | barcelos
Processing Record 22 of Set  4 | bayshore gardens
Processing Record 23 of Set  4 | kavieng
Processing Record 24 of Set  4 | takoradi
Processing Record 25 of Set  4 | barentsburg
City not found. Skipping...
Processing Record 25 of Set  4 | sao geraldo do araguaia
Processing Record 26 of Set  4 | ajdabiya
Processing Record 27 of Set  4 | alta floresta
Processing Record 28 of Set  4 | faya
Processing Record 29 of Set  4 | bonthe
Processing Record 30 of Set  4 | amarillo
Processing Record 31 of Set  4 | linxia
Processing Record 32 of Set  4 | aiken
Processing Record 33 of Set  4 | saint-augustin
Processing Record 34 of Set  4 | homer
Processing Record 35 of Set  4 | vao
Processing Record 36 of Set  4 | miraflores
Processing Record 37 of Set  4 | lensk
Processing Record 38 of Set  4 | edd
Processing Record 39 of Set  4 | zhangjiakou
Processing Record 40 of Set  4 | hasaki
Processing Record 41 of Set  4 | aripuana
Processing Record 42 of Set  4 | mujiayingzi
Processing Record 43 of Set  4 | cayenne
Processing Record 44 of Set  4 | atambua
Processing Record 45 of Set  4 | mahebourg
Processing Record 46 of Set  4 | aracaju
Processing Record 47 of Set  4 | saleaula
City not found. Skipping...
Processing Record 47 of Set  4 | severnyy
Processing Record 48 of Set  4 | islahiye
Processing Record 49 of Set  4 | roald
Processing Record 0 of Set  5 | yulara
Processing Record 1 of Set  5 | esperance
Processing Record 2 of Set  5 | tiksi
Processing Record 3 of Set  5 | komsomolskoye
Processing Record 4 of Set  5 | shimoda
Processing Record 5 of Set  5 | vardo
Processing Record 6 of Set  5 | port hawkesbury
Processing Record 7 of Set  5 | koslan
Processing Record 8 of Set  5 | banyo
Processing Record 9 of Set  5 | mosquera
Processing Record 10 of Set  5 | gold coast
Processing Record 11 of Set  5 | pucara
Processing Record 12 of Set  5 | samusu
City not found. Skipping...
Processing Record 12 of Set  5 | richards bay
Processing Record 13 of Set  5 | verkhnevilyuysk
Processing Record 14 of Set  5 | nhulunbuy
Processing Record 15 of Set  5 | bredasdorp
Processing Record 16 of Set  5 | bethel
Processing Record 17 of Set  5 | charleville-mezieres
Processing Record 18 of Set  5 | aswan
Processing Record 19 of Set  5 | matara
Processing Record 20 of Set  5 | havelock
Processing Record 21 of Set  5 | gat
Processing Record 22 of Set  5 | borazjan
Processing Record 23 of Set  5 | chara
Processing Record 24 of Set  5 | grafton
Processing Record 25 of Set  5 | hof
Processing Record 26 of Set  5 | nieves
Processing Record 27 of Set  5 | brasileia
Processing Record 28 of Set  5 | xinyang
Processing Record 29 of Set  5 | georgetown
Processing Record 30 of Set  5 | brits
Processing Record 31 of Set  5 | san juan
Processing Record 32 of Set  5 | biak
Processing Record 33 of Set  5 | campeche
Processing Record 34 of Set  5 | opuwo
Processing Record 35 of Set  5 | inhambane
Processing Record 36 of Set  5 | kinablangan
Processing Record 37 of Set  5 | rocha
Processing Record 38 of Set  5 | pangnirtung
Processing Record 39 of Set  5 | lundamo
Processing Record 40 of Set  5 | port hedland
Processing Record 41 of Set  5 | samarai
Processing Record 42 of Set  5 | strathmore
Processing Record 43 of Set  5 | henties bay
Processing Record 44 of Set  5 | teteven
Processing Record 45 of Set  5 | zhigansk
Processing Record 46 of Set  5 | la orilla
Processing Record 47 of Set  5 | zonguldak
Processing Record 48 of Set  5 | suez
Processing Record 49 of Set  5 | clyde river
Processing Record 0 of Set  6 | emba
Processing Record 1 of Set  6 | japura
Processing Record 2 of Set  6 | iqaluit
Processing Record 3 of Set  6 | port lincoln
Processing Record 4 of Set  6 | laureles
Processing Record 5 of Set  6 | dano
Processing Record 6 of Set  6 | pacific grove
Processing Record 7 of Set  6 | tazovskiy
Processing Record 8 of Set  6 | mount gambier
Processing Record 9 of Set  6 | solnechnyy
Processing Record 10 of Set  6 | qianan
Processing Record 11 of Set  6 | tuatapere
Processing Record 12 of Set  6 | sitka
Processing Record 13 of Set  6 | aden
Processing Record 14 of Set  6 | tarko-sale
Processing Record 15 of Set  6 | tasiilaq
Processing Record 16 of Set  6 | shuangcheng
Processing Record 17 of Set  6 | krasnoselkup
Processing Record 18 of Set  6 | nome
Processing Record 19 of Set  6 | sao felix do xingu
Processing Record 20 of Set  6 | kiama
Processing Record 21 of Set  6 | kisangani
Processing Record 22 of Set  6 | thinadhoo
Processing Record 23 of Set  6 | uyuni
Processing Record 24 of Set  6 | hithadhoo
Processing Record 25 of Set  6 | yuzha
Processing Record 26 of Set  6 | batemans bay
Processing Record 27 of Set  6 | sayansk
Processing Record 28 of Set  6 | nizhneyansk
City not found. Skipping...
Processing Record 28 of Set  6 | grootegast
Processing Record 29 of Set  6 | san cristobal
Processing Record 30 of Set  6 | mouzakion
City not found. Skipping...
Processing Record 30 of Set  6 | sarankhola
Processing Record 31 of Set  6 | paamiut
Processing Record 32 of Set  6 | anadyr
Processing Record 33 of Set  6 | louisbourg
City not found. Skipping...
Processing Record 33 of Set  6 | korla
Processing Record 34 of Set  6 | fianarantsoa
Processing Record 35 of Set  6 | hami
Processing Record 36 of Set  6 | visby
Processing Record 37 of Set  6 | salamanca
Processing Record 38 of Set  6 | souillac
Processing Record 39 of Set  6 | witu
Processing Record 40 of Set  6 | orlik
Processing Record 41 of Set  6 | ormara
Processing Record 42 of Set  6 | tavda
Processing Record 43 of Set  6 | asau
Processing Record 44 of Set  6 | jiaxing
Processing Record 45 of Set  6 | pathardi
Processing Record 46 of Set  6 | dondo
Processing Record 47 of Set  6 | leningradskiy
Processing Record 48 of Set  6 | lollar
Processing Record 49 of Set  6 | suntar
Processing Record 0 of Set  7 | labuhan
Processing Record 1 of Set  7 | usinsk
Processing Record 2 of Set  7 | khor
Processing Record 3 of Set  7 | havre-saint-pierre
Processing Record 4 of Set  7 | kushiro
Processing Record 5 of Set  7 | tomatlan
Processing Record 6 of Set  7 | erzin
Processing Record 7 of Set  7 | fortuna
Processing Record 8 of Set  7 | mahroni
Processing Record 9 of Set  7 | palmer
Processing Record 10 of Set  7 | itacoatiara
Processing Record 11 of Set  7 | dingle
Processing Record 12 of Set  7 | bac lieu
Processing Record 13 of Set  7 | zwedru
Processing Record 14 of Set  7 | praia da vitoria
Processing Record 15 of Set  7 | daru
Processing Record 16 of Set  7 | constitucion
Processing Record 17 of Set  7 | qaqortoq
Processing Record 18 of Set  7 | sobolevo
Processing Record 19 of Set  7 | sale
Processing Record 20 of Set  7 | rogongon
Processing Record 21 of Set  7 | dunedin
Processing Record 22 of Set  7 | mayo
Processing Record 23 of Set  7 | natal
Processing Record 24 of Set  7 | ponta delgada
Processing Record 25 of Set  7 | bathsheba
Processing Record 26 of Set  7 | barra do garcas
Processing Record 27 of Set  7 | verkhniy mamon

Processing Record 28 of Set  7 | tucuma
Processing Record 29 of Set  7 | brownsville
Processing Record 30 of Set  7 | puliyankudi
Processing Record 31 of Set  7 | bilibino
Processing Record 32 of Set  7 | samana
Processing Record 33 of Set  7 | mesyagutovo
Processing Record 34 of Set  7 | tonj
Processing Record 35 of Set  7 | limulunga
Processing Record 36 of Set  7 | magnitogorsk
Processing Record 37 of Set  7 | ocumare del tuy
Processing Record 38 of Set  7 | wageningen
Processing Record 39 of Set  7 | ramnagar
Processing Record 40 of Set  7 | mayor pablo lagerenza
Processing Record 41 of Set  7 | ribeira grande
Processing Record 42 of Set  7 | ardakan
Processing Record 43 of Set  7 | faanui
Processing Record 44 of Set  7 | te anau
Processing Record 45 of Set  7 | arlit
Processing Record 46 of Set  7 | guerrero negro
Processing Record 47 of Set  7 | auki
Processing Record 48 of Set  7 | ambovombe
Processing Record 49 of Set  7 | namibe
Processing Record 0 of Set  8 | athmallik
Processing Record 1 of Set  8 | gondanglegi
Processing Record 2 of Set  8 | kaitangata
Processing Record 3 of Set  8 | galiwinku
City not found. Skipping...
Processing Record 3 of Set  8 | dalbandin
Processing Record 4 of Set  8 | necochea
Processing Record 5 of Set  8 | nanortalik
Processing Record 6 of Set  8 | pandan
Processing Record 7 of Set  8 | omsukchan
Processing Record 8 of Set  8 | palu
Processing Record 9 of Set  8 | san andres
Processing Record 10 of Set  8 | urusha
Processing Record 11 of Set  8 | constantine
Processing Record 12 of Set  8 | banjar
Processing Record 13 of Set  8 | marzuq
Processing Record 14 of Set  8 | lata
Processing Record 15 of Set  8 | bria
Processing Record 16 of Set  8 | naze
Processing Record 17 of Set  8 | son la
Processing Record 18 of Set  8 | satitoa
City not found. Skipping...
Processing Record 18 of Set  8 | ostrovnoy
Processing Record 19 of Set  8 | buchanan
Processing Record 20 of Set  8 | quattro castella
Processing Record 21 of Set  8 | camacha
Processing Record 22 of Set  8 | korem
Processing Record 23 of Set  8 | esso
Processing Record 24 of Set  8 | fernie
Processing Record 25 of Set  8 | lasa
Processing Record 26 of Set  8 | imphal
Processing Record 27 of Set  8 | qasigiannguit
Processing Record 28 of Set  8 | atasu
Processing Record 29 of Set  8 | norwich
Processing Record 30 of Set  8 | lamar
Processing Record 31 of Set  8 | oktyabrskoye
Processing Record 32 of Set  8 | yeppoon
Processing Record 33 of Set  8 | codrington
Processing Record 34 of Set  8 | coihaique
Processing Record 35 of Set  8 | nguruka
Processing Record 36 of Set  8 | matamoros
Processing Record 37 of Set  8 | chuguyevka
Processing Record 38 of Set  8 | puerto carreno
Processing Record 39 of Set  8 | fare
Processing Record 40 of Set  8 | penha
Processing Record 41 of Set  8 | zapolyarnyy
Processing Record 42 of Set  8 | drayton valley
Processing Record 43 of Set  8 | karratha
Processing Record 44 of Set  8 | chino valley
Processing Record 45 of Set  8 | kirakira
Processing Record 46 of Set  8 | gull lake
Processing Record 47 of Set  8 | taos
Processing Record 48 of Set  8 | parrita
Processing Record 49 of Set  8 | naron
Processing Record 0 of Set  9 | ancud
Processing Record 1 of Set  9 | longlac
City not found. Skipping...
Processing Record 1 of Set  9 | seoul
Processing Record 2 of Set  9 | sisimiut
Processing Record 3 of Set  9 | lithakia
Processing Record 4 of Set  9 | noumea
Processing Record 5 of Set  9 | candelaria
Processing Record 6 of Set  9 | sentyabrskiy
City not found. Skipping...
Processing Record 6 of Set  9 | tungor
Processing Record 7 of Set  9 | ashcroft
Processing Record 8 of Set  9 | shelburne
Processing Record 9 of Set  9 | cabo san lucas
Processing Record 10 of Set  9 | west plains
Processing Record 11 of Set  9 | boa vista
Processing Record 12 of Set  9 | banda aceh
Processing Record 13 of Set  9 | tezu
Processing Record 14 of Set  9 | toamasina
Processing Record 15 of Set  9 | prudentopolis
Processing Record 16 of Set  9 | biharamulo
Processing Record 17 of Set  9 | marawi
Processing Record 18 of Set  9 | laon
Processing Record 19 of Set  9 | dutse
Processing Record 20 of Set  9 | caconda
Processing Record 21 of Set  9 | khasan
Processing Record 22 of Set  9 | lewistown
Processing Record 23 of Set  9 | neyveli
Processing Record 24 of Set  9 | popondetta
Processing Record 25 of Set  9 | khormuj
City not found. Skipping...
Processing Record 25 of Set  9 | san patricio
Processing Record 26 of Set  9 | negombo
Processing Record 27 of Set  9 | dauriya
Processing Record 28 of Set  9 | geraldton
Processing Record 29 of Set  9 | lavrentiya
Processing Record 30 of Set  9 | berlevag
Processing Record 31 of Set  9 | sioux lookout
Processing Record 32 of Set  9 | sarila
Processing Record 33 of Set  9 | ixtapa
Processing Record 34 of Set  9 | majene
Processing Record 35 of Set  9 | kenai
Processing Record 36 of Set  9 | shingu
Processing Record 37 of Set  9 | jardim
Processing Record 38 of Set  9 | vanavara
Processing Record 39 of Set  9 | otane
Processing Record 40 of Set  9 | auch
Processing Record 41 of Set  9 | cesis
Processing Record 42 of Set  9 | saint-georges
Processing Record 43 of Set  9 | bonavista
Processing Record 44 of Set  9 | bandarbeyla
Processing Record 45 of Set  9 | talnakh
Processing Record 46 of Set  9 | klaksvik
Processing Record 47 of Set  9 | yarada
Processing Record 48 of Set  9 | tayu
Processing Record 49 of Set  9 | bundaberg
Processing Record 0 of Set  10 | cabra
Processing Record 1 of Set  10 | nyurba
Processing Record 2 of Set  10 | remanso
Processing Record 3 of Set  10 | ambilobe
Processing Record 4 of Set  10 | khowst
Processing Record 5 of Set  10 | coahuayana
Processing Record 6 of Set  10 | ahipara
Processing Record 7 of Set  10 | omboue
Processing Record 8 of Set  10 | paranhos
Processing Record 9 of Set  10 | imabari
City not found. Skipping...
Processing Record 9 of Set  10 | bonito
Processing Record 10 of Set  10 | russell
Processing Record 11 of Set  10 | gorin
Processing Record 12 of Set  10 | veshenskaya
Processing Record 13 of Set  10 | boyuibe
Processing Record 14 of Set  10 | morag
Processing Record 15 of Set  10 | itamaraca
Processing Record 16 of Set  10 | urozhaynoye
Processing Record 17 of Set  10 | ola
Processing Record 18 of Set  10 | alexandria
Processing Record 19 of Set  10 | varkaus
Processing Record 20 of Set  10 | karaton
Processing Record 21 of Set  10 | zomin
Processing Record 22 of Set  10 | teya
Processing Record 23 of Set  10 | china
Processing Record 24 of Set  10 | palauig
Processing Record 25 of Set  10 | burica
City not found. Skipping...
Processing Record 25 of Set  10 | annigeri
Processing Record 26 of Set  10 | boda
Processing Record 27 of Set  10 | igarka
Processing Record 28 of Set  10 | storforshei
Processing Record 29 of Set  10 | australind
Processing Record 30 of Set  10 | dicabisagan
Processing Record 31 of Set  10 | chuy
Processing Record 32 of Set  10 | tzermiadon
City not found. Skipping...
Processing Record 32 of Set  10 | udachnyy
Processing Record 33 of Set  10 | mogadishu
Processing Record 34 of Set  10 | burnie
Processing Record 35 of Set  10 | kaseda
Processing Record 36 of Set  10 | phek
Processing Record 37 of Set  10 | tabou
Processing Record 38 of Set  10 | tsaratanana
Processing Record 39 of Set  10 | ust-maya
Processing Record 40 of Set  10 | magistralnyy
Processing Record 41 of Set  10 | maridi
Processing Record 42 of Set  10 | bondoukou
Processing Record 43 of Set  10 | coos bay
Processing Record 44 of Set  10 | jinchengjiang
City not found. Skipping...
Processing Record 44 of Set  10 | bol
Processing Record 45 of Set  10 | chiang rai
Processing Record 46 of Set  10 | fartura
Processing Record 47 of Set  10 | krasnyy chikoy
Processing Record 48 of Set  10 | ust-kuyga
Processing Record 49 of Set  10 | ape
Processing Record 0 of Set  11 | nevel
Processing Record 1 of Set  11 | belmonte
Processing Record 2 of Set  11 | nurota
Processing Record 3 of Set  11 | kerzhenets
City not found. Skipping...
Processing Record 3 of Set  11 | port keats

Processing Record 4 of Set  11 | petropavlovskoye
Processing Record 5 of Set  11 | imbituba
Processing Record 6 of Set  11 | liuzhou
Processing Record 7 of Set  11 | srivardhan
Processing Record 8 of Set  11 | hastings
Processing Record 9 of Set  11 | rungata
City not found. Skipping...
Processing Record 9 of Set  11 | chalmette
Processing Record 10 of Set  11 | khani
Processing Record 11 of Set  11 | caravelas
Processing Record 12 of Set  11 | san ignacio
Processing Record 13 of Set  11 | inverness
Processing Record 14 of Set  11 | prince rupert
Processing Record 15 of Set  11 | rio gallegos
Processing Record 16 of Set  11 | san carlos de bariloche
Processing Record 17 of Set  11 | kankaanpaa
Processing Record 18 of Set  11 | barahona
Processing Record 19 of Set  11 | kralendijk
Processing Record 20 of Set  11 | castleblayney
Processing Record 21 of Set  11 | watertown
Processing Record 22 of Set  11 | calvinia
Processing Record 23 of Set  11 | oistins
Processing Record 24 of Set  11 | mazeikiai
Processing Record 25 of Set  11 | sistranda
Processing Record 26 of Set  11 | celestun
Processing Record 27 of Set  11 | maarianhamina
Processing Record 28 of Set  11 | serik
Processing Record 29 of Set  11 | lagoa
Processing Record 30 of Set  11 | san cosme y damian
Processing Record 31 of Set  11 | warrington
Processing Record 32 of Set  11 | malwan
City not found. Skipping...
Processing Record 32 of Set  11 | nizwa
Processing Record 33 of Set  11 | vestmanna
Processing Record 34 of Set  11 | juba
Processing Record 35 of Set  11 | keti bandar
Processing Record 36 of Set  11 | otjiwarongo
Processing Record 37 of Set  11 | pevek
Processing Record 38 of Set  11 | whitianga
Processing Record 39 of Set  11 | kadykchan
City not found. Skipping...
Processing Record 39 of Set  11 | muisne
Processing Record 40 of Set  11 | paris
Processing Record 41 of Set  11 | tari
Processing Record 42 of Set  11 | la asuncion
Processing Record 43 of Set  11 | may pen
Processing Record 44 of Set  11 | sao lourenco do sul
Processing Record 45 of Set  11 | acapulco
Processing Record 46 of Set  11 | west bay
Processing Record 47 of Set  11 | phan thiet
Processing Record 48 of Set  11 | gorno-chuyskiy
City not found. Skipping...
Processing Record 48 of Set  11 | zaragoza
Processing Record 49 of Set  11 | point fortin
Processing Record 0 of Set  12 | boyolangu
Processing Record 1 of Set  12 | kachikau
City not found. Skipping...
Processing Record 1 of Set  12 | walvis bay
Processing Record 2 of Set  12 | sarangani
Processing Record 3 of Set  12 | ornskoldsvik
Processing Record 4 of Set  12 | mangaluru
Processing Record 5 of Set  12 | skjervoy
Processing Record 6 of Set  12 | puerto escondido
Processing Record 7 of Set  12 | riyadh
Processing Record 8 of Set  12 | kemijarvi
Processing Record 9 of Set  12 | zdunska wola
Processing Record 10 of Set  12 | borshchiv
Processing Record 11 of Set  12 | komsomolskiy
Processing Record 12 of Set  12 | nueva helvecia
Processing Record 13 of Set  12 | umzimvubu
City not found. Skipping...
Processing Record 13 of Set  12 | houma
Processing Record 14 of Set  12 | sujiatun
Processing Record 15 of Set  12 | lakes entrance
Processing Record 16 of Set  12 | hobyo
Processing Record 17 of Set  12 | taltal
Processing Record 18 of Set  12 | quesnel
Processing Record 19 of Set  12 | eskasem
City not found. Skipping...
Processing Record 19 of Set  12 | lakselv
Processing Record 20 of Set  12 | la ronge
Processing Record 21 of Set  12 | grand centre
City not found. Skipping...
Processing Record 21 of Set  12 | nekhayevskiy
Processing Record 22 of Set  12 | artyom
Processing Record 23 of Set  12 | ankang
Processing Record 24 of Set  12 | mpongwe
Processing Record 25 of Set  12 | guadalupe y calvo
Processing Record 26 of Set  12 | preobrazheniye
Processing Record 27 of Set  12 | upata
Processing Record 28 of Set  12 | kyabe
Processing Record 29 of Set  12 | maldonado
Processing Record 30 of Set  12 | kaili
Processing Record 31 of Set  12 | macapa
Processing Record 32 of Set  12 | portobelo
Processing Record 33 of Set  12 | tucumcari
Processing Record 34 of Set  12 | tucuman
Processing Record 35 of Set  12 | garowe
Processing Record 36 of Set  12 | balykshi
Processing Record 37 of Set  12 | tondano
Processing Record 38 of Set  12 | chaman
Processing Record 39 of Set  12 | wana
------------------------
Data Retrieval Complete
------------------------

In [12]:
citiesToProcess.to_csv(r'../output_data/city_data.csv')

In [14]:
citiesToProcess

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Jamestown,42.097,-79.2353,65.84,68,0,1.01,US,1658898514
1,taolanaro,,,,,,,,
2,Kapaa,22.0752,-159.319,82.38,82,75,18.41,US,1658898797
3,Hermanus,-34.4187,19.2345,47.8,85,31,6.26,ZA,1658898799
4,palabuhanratu,,,,,,,,
...,...,...,...,...,...,...,...,...,...
643,Garoowe,8.4054,48.4845,92.17,29,59,25.79,SO,1658924300
644,Balyqshy,47.0667,51.8667,89.6,37,75,20.13,KZ,1658924303
645,Tondano,1.3038,124.9112,71.69,95,100,3.15,ID,1658924306
646,Chaman,30.9236,66.4512,91.67,38,66,6.58,PK,1658924308
647,Wana,32.2989,69.5725,82.33,60,81,8.03,PK,1658924311

In [22]:
print (citiesToProcess.dtypes)

City          object
Lat           object
Lng           object
Max Temp      object
Humidity      object
Cloudiness    object
Wind Speed    object
Country       object
Date          object
dtype: object

In [24]:
citiesToProcess.describe()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
count,648,648,648,648,648,648,648,648,648
unique,648,587,590,542,86,97,320,124,569
top,Jamestown,,,,,100,,RU,
freq,1,59,59,59,59,101,59,76,59

In [33]:
citiesToProcess['Humidity']=citiesToProcess['Humidity'].astype(int)

ValueError: invalid literal for int() with base 10: ''

### Perform API Calls
* Perform a weather check on each city using a series of successive API calls.
* Include a print log of each city as it'sbeing processed (with the city number and city name).

### Convert Raw Data to DataFrame
* Export the city data into a .csv.
* Display the DataFrame

## Inspect the data and remove the cities where the humidity > 100%.
----
Skip this step if there are no cities that have humidity > 100%.

In [ ]:
#  Get the indices of cities that have humidity over 100%.

In [ ]:
# Make a new DataFrame equal to the city data to drop all humidity outliers by index.
# Passing "inplace=False" will make a copy of the city_data DataFrame, which we call "clean_city_data".

## Plotting the Data
* Use proper labeling of the plots using plot titles (including date of analysis) and axes labels.
* Save the plotted figures as .pngs.

## Latitude vs. Temperature Plot

## Latitude vs. Humidity Plot

## Latitude vs. Cloudiness Plot

## Latitude vs. Wind Speed Plot

## Linear Regression

####  Northern Hemisphere - Max Temp vs. Latitude Linear Regression

####  Southern Hemisphere - Max Temp vs. Latitude Linear Regression

####  Northern Hemisphere - Humidity (%) vs. Latitude Linear Regression

####  Southern Hemisphere - Humidity (%) vs. Latitude Linear Regression

####  Northern Hemisphere - Cloudiness (%) vs. Latitude Linear Regression

####  Southern Hemisphere - Cloudiness (%) vs. Latitude Linear Regression

####  Northern Hemisphere - Wind Speed (mph) vs. Latitude Linear Regression

####  Southern Hemisphere - Wind Speed (mph) vs. Latitude Linear Regression